drop table ei09689.tlds;
CREATE TABLE EI09689.TLDS AS (
select 
Q2.REGION as "ASSIGNMENT_REGION",
Q1.RESPONSIBLE_COUNTY_DESC,
Q1.SUPERVISOR_NAME,
Q1.WORKER_NAME,
Q1.CASE_ID,
Q1.PERSON_ID,
Q1.PERSON_NAME,
Q1.CURRENT_AGE,
Q1.BIRTH_DATE,
Q1.SSN,
Q1.ALIEN_STATUS,
Q1.GENDER_DESC,
Q1.CHILD_RACE,
Q1.HISPANIC_LATINO_CODE,
Q1.CUSTODY_START_DATE,
Q1.CUSTODY_END_DATE,
trunc((nvl(Q1.CUSTODY_END_DATE,sysdate))-Q1.CUSTODY_START_DATE) as "DAYS_IN_CUSTODY",
Q1.ADJUDICATION_DESC,
CASE WHEN Q1.INITIAL_LEGAL_STATUS = 'DCSCUSTER' THEN 'Y' ELSE NULL END "EMER_CUSTODY_FLAG",
Q1.JJ_TYPE,
NVL(Q1.CUSTODY_END_DATE,TRUNC(sysdate))-Q1.CUSTODY_START_DATE  "NUMBER_OF_DAYS_IN_CUSTODY",
Q1.REMOVAL_REASON_DESC AS "CUSTODY_REASON",
Q1.RELEASE_REASON_DESC as "RELEASE_REASON",
Q1.REM_ADDR AS "REMOVAL_ADDRESS",
Q1.REM_CITY AS "REMOVAL_CITY",
Q1.REM_STATE_CODE AS "REMOVAL_STATE",
Q1.REM_ZIP5_CODE AS "REMOVAL_ZIP_CODE",
Q1.REMOVAL_COUNTY_DESC AS  "REMOVAL_COUNTY",
Q1.REMOVAL_REGION as "REMOVAL_REGION",
Q1.GUARDIANSHIP_TYPE_DESC as "GUARDIANSHIP_STATUS",
Q1.EFFECTIVE_DATE as "GUARDIANSHIP_EFFECTVE_DATE",
Q1.MAX_TPR_DATE as "TPR_PETITION_DATE",
Q1.MAX_VOL_SUR_DATE as "VOLSURRENDER_CERTDEATH_DATE",
Q1.PLAN_DATE AS "PP_DATE",
CASE WHEN Q1.SAPG_STATUS = ('Expired') THEN NULL 
ELSE Q1.GOAL_DESC1 
END AS "PP_GOAL_1",
CASE WHEN Q1.SAPG_STATUS = ('Expired') THEN NULL 
ELSE Q1.ESTABLISHED_DATE1
END AS "PP_GOAL_1_EDATE",
CASE WHEN Q1.SAPG_STATUS = ('Expired') THEN NULL 
else Q1.TARGET_DATE1
END AS "PP_GOAL_1_TDATE",
CASE WHEN Q1.SAPG_STATUS = ('Expired') THEN NULL
ELSE  ((CURRENT_DATE - Q1.ESTABLISHED_DATE1) / 31)
END AS  "MONTHS_GOAL1_ESTAB",
CASE WHEN Q1.SAPG_STATUS = ('Expired') THEN NULL 
else Q1.GOAL_DESC2
END AS "PP_GOAL_2",
CASE WHEN Q1.SAPG_STATUS = ('Expired') THEN NULL 
ELSE Q1.ESTABLISHED_DATE2
END AS "PP_GOAL_2_EDATE",
CASE WHEN Q1.SAPG_STATUS = ('Expired') THEN NULL 
else Q1.TARGET_DATE2
END AS "PP_GOAL_2_TDATE",
CASE WHEN Q1.SAPG_STATUS = ('Expired') THEN NULL
ELSE  ((CURRENT_DATE - Q1.ESTABLISHED_DATE2) / 31)
End As  "MONTHS_GOAL2_ESTAB",
Q1.VENDOR_NAME AS "PLACEMENT_RESOURCE_NAME",
Q1.PLACEMENT_LOCATION_NAME AS "PLACEMENT_LOCATION",
Q1.PLACEMENT_BEGIN_DATE AS "PLACEMENT_BEGIN_DATE",
Q1.PLACEMENT_END_DATE AS "PLACEMENT_END_DATE",
Q1.PLACEMENT_TYPE_DESC AS "PLACEMENT_TYPE",
Q1.PLACEMENT_SERVICE_TYPE AS "PLACEMENT_SETTING",
Q1.LOS_PLACEMENT AS "NUMBER_OF_DAYS_IN_PLACEMENT",
Q1.PROVIDER_RELATIONSHIP_DESC as "KINSHIP_ROLE",
Q1.STREET_ADDRESS AS "PLACEMENT_ADDRESS",
Q1.CITY_NAME as "PLACEMENT_CITY",
Q1.STATE_CODE as "PLACEMENT_STATE",
Q1.ZIP5_CODE as "PLACEMENT_ZIP_CODE",
Q1.COUNTY_NAME as "PLACEMENT_COUNTY",
Q1.REGION as "PLACEMENT_REGION",
Q1.PARTY_CONTACT as "PLACEMENT_TELEPHONE_NUMBER",
Q1.INTENT_TO_ADOPT_DATE AS "INTEND_TO_ADOPT_DATE",
Q1.OFFENSE_CLASS AS "OFFENSE_CATEGORY",
Q1.OFFENSE_DESC AS "OFFENSE",
Q1.SCHOOL_NAME1,
CASE WHEN Q1.EDU_END_DATE IS NULL THEN Q1.BEGIN_GRADE_CD ELSE Q1.END_GRADE_CD END "SCHOOL_GRADE",
Q1.PREV_CUSTODY_START_DATE,
Q1.PREV_CUSTODY_END_DATE,
Case When Nvl(Q1.Custody_End_Date,Trunc(Sysdate))-Q1.Custody_Start_Date  <= 90 Then '0-90_DAYS'  
When Nvl(Q1.Custody_End_Date,Trunc(Sysdate))-Q1.Custody_Start_Date  Between 91 And 182.58 Then '90_DAYS_TO_MONTHS'
When Nvl(Q1.Custody_End_Date,Trunc(Sysdate))-Q1.Custody_Start_Date  Between 182.59 And 273.87 Then '6_MONTHS_TO_9_MONTHS'
When Nvl(Q1.Custody_End_Date,Trunc(Sysdate))-Q1.Custody_Start_Date  Between 273.88 And 365.25 Then '9_MONTHS_TO_12_MONTHS'
When Nvl(Q1.Custody_End_Date,Trunc(Sysdate))-Q1.Custody_Start_Date  Between 365.26 And 456.45 Then '12_MONTHS_TO_15_MONTHS'
WHEN NVL(Q1.CUSTODY_END_DATE,TRUNC(SYSDATE))-Q1.CUSTODY_START_DATE  >=  456.46 THEN '15_MONTHS_OR_GREATER'
ELSE NULL
END AS "CUSTODY_LOS_RANGE",	
CASE WHEN NVL(Q1.CUSTODY_END_DATE,TRUNC(SYSDATE))-Q1.CUSTODY_START_DATE BETWEEN 426.02 AND 456.46 THEN 'Y'
ELSE NULL
end as "CLIENTS_IN_CUSTODY_14",
Q1.COMP_RSN_FLAG AS "TPR_EXCEPTION_CR",
Q1.CONF_EXP_DATE AS "TPR_EXCEPTION_CR_DATE",
CASE WHEN Q1.CUSTODY_END_DATE IS NOT NULL THEN
Q1.FOWARDING_ADDRESS
END AS "FORWARDING_ADDRESS",
CASE WHEN Q1.CUSTODY_END_DATE IS NOT NULL THEN 
Q1.FORWARDING_CITY
END AS "FORWARDING_CITY",
CASE WHEN Q1.CUSTODY_END_DATE IS NOT NULL THEN 
Q1.FORWARDING_STATE
END AS "FORWARDING_STATE",
CASE WHEN Q1.CUSTODY_END_DATE IS NOT NULL THEN 
Q1.FORWARDING_ZIP
end as "FORWARDING_ZIP",
Q1.EDUC_DIS1 as "IEP_DISABILITY1",
Q1.EDUC_DIS2 as "IEP_DISABILITY2",
Q1.EDUC_DIS3 as "IEP_DISABILITY3",
Q1.EDUC_DIS4 as "IEP_DISABILITY4",
Q1.EDUC_DIS5 AS "IEP_DISABILITY5",
Q1.EDU_EFFECTIVE_DATE AS "IEP_EFFECTIVE_DATE",
Q1.EDU_EXPIRATION_DATE as "IEP_EXPIRATION_DATE",
Q3.REGION as "COMMITMENT_REGION",
Q1.COMMITMENT_COUNTY_DESC  AS "COMMITMENT_COUNTY"
FROM  L2_OWNER.STG_MEGA_BASE9 Q1
LEFT JOIN L2_OWNER.DIM_AGENCY Q2 ON
Q1.RESPONSIBLE_AGENCY_ID = Q2.AGENCY_ID
LEFT JOIN L2_OWNER.DIM_AGENCY Q3 ON
Q1.COMMITMENT_AGENCY_ID = Q3.AGENCY_ID
WHERE ROWNUM<100
)
;




